### ISSUE TITLE
NansException when using new samplers 

### ISSUE THREAD

**Issue by AndreyRGW** [DenOfEquity/webUI_ExtraSchedulers#2]
![image](https://github.com/user-attachments/assets/54e4f668-1640-47d1-8c62-0d2f14e459f7)

NansException: A tensor with NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

```
    Traceback (most recent call last):
      File "F:\WBC\automatic1111_dev\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "F:\WBC\automatic1111_dev\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "F:\WBC\automatic1111_dev\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "F:\WBC\automatic1111_dev\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "F:\WBC\automatic1111_dev\modules\processing.py", line 847, in process_images
        res = process_images_inner(p)
      File "F:\WBC\automatic1111_dev\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 59, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\WBC\automatic1111_dev\modules\processing.py", line 998, in process_images_inner
        devices.test_for_nans(samples_ddim, "unet")
      File "F:\WBC\automatic1111_dev\modules\devices.py", line 265, in test_for_nans
        raise NansException(message)
    modules.devices.NansException: A tensor with NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

---
```

**Comment by DenOfEquity** [comment]
The method used for CFG++ doesn't work in A1111, *last_noise_uncond* is set differently. I've done some testing to see if I can easily make it work, without success.
I'll probably just add a check to not show the samplers in A1111.

**Comment by anon0730** [comment]
There seems to be some kind of problem with this "A1111 check" as I'm on latest version of Forge (main branch) and installing this extension only adds the other two new samplers and the new schedulers but does not add any of the CFG++ samplers to the sampler selection.

![image](https://github.com/user-attachments/assets/0c570965-8b23-4c8a-af44-8cbcb0ee8f4e)

For now I am using commit 9639a11 and CFG++ seems to be working fine though this version is missing some of the newer additions.

**Comment by DenOfEquity** [comment]
Thanks for pointing this out.
Problem was down to a goofed import - `main` branch is a cut down version of the more experimental `neg` branch.

**Comment by anon0730** [comment]
I just pulled and it works without issue now with the latest commit. Thanks.
